Repository RubyNaxela/softeng, pull requests merged in 2023-12, with the labels that each got.

#2 Added Inverse function
  src/main/java/pl/put/poznan/transformer/logic/transform/Inverse.java
  src/main/java/pl/put/poznan/transformer/rest/TextTransformerClass.java
  src/main/java/pl/put/poznan/transformer/rest/TextTransformerController.java
  src/test/java/pl/put/poznan/transformer/logic/transform/InverseTest.java
Labels: enhancement, test

#3 Minor changes. Added Javadoc
  src/main/java/pl/put/poznan/transformer/logic/TextClass.java
  src/main/java/pl/put/poznan/transformer/logic/TextTransformer.java
  src/main/java/pl/put/poznan/transformer/logic/TextTransformerDecorator.java
  src/main/java/pl/put/poznan/transformer/logic/transform/NeighDel.java
  src/main/java/pl/put/poznan/transformer/logic/transform/ShortcutMod.java
  src/main/java/pl/put/poznan/transformer/logic/transform/ToLaTeX.java
  src/main/java/pl/put/poznan/transformer/logic/transform/Transform.java
  src/main/java/pl/put/poznan/transformer/rest/TextTransformerClass.java
  src/main/java/pl/put/poznan/transformer/rest/TextTransformerController.java
Labels: documentation

#5 Many files updated
  .gitignore
  pom.xml
  src/test/java/pl/put/poznan/transformer/app/TextTransformerApplicationTest.java
Labels: enhancement, test

#6 My main
  README.md
  src/main/java/pl/put/poznan/transformer/rest/TextTransformerController.java
Labels: enhancement

#8 dar1
  Diagramy UML.md
Labels: small fix

#12 Separate Client and Server folders. Update pom files. Update JDK 17,
  .github/workflows/maven.yml
  .gitignore
  Client/pom.xml
  Client/src/main/java/pl/put/poznan/transformer/client/GlobalContext.java
  Client/src/main/java/pl/put/poznan/transformer/client/TextTransformerClient.java
  Client/src/main/java/pl/put/poznan/transformer/client/data/ServicesList.java
  Client/src/main/java/pl/put/poznan/transformer/client/data/TransformRequest.java
  Client/src/main/java/pl/put/poznan/transformer/client/data/TransformResponse.java
  Client/src/main/java/pl/put/poznan/transformer/client/gui/HostAndPortSelectPopup.java
  Client/src/main/java/pl/put/poznan/transformer/client/gui/MainWindow.java
  Client/src/main/java/pl/put/poznan/transformer/client/gui/Messages.java
  Client/src/main/java/pl/put/poznan/transformer/client/gui/ServicesDropdownList.java
  Client/src/main/java/pl/put/poznan/transformer/client/gui/WrapLabel.java
  Client/src/main/java/pl/put/poznan/transformer/client/rest/RESTController.java
  Server/pom.xml
  Server/src/main/java/pl/put/poznan/transformer/server/app/TextTransformerServer.java
  Server/src/main/java/pl/put/poznan/transformer/server/logic/TextTransformer.java
  Server/src/main/java/pl/put/poznan/transformer/server/logic/TextTransformerDecorator.java
  Server/src/main/java/pl/put/poznan/transformer/server/logic/TransformerBase.java
  Server/src/main/java/pl/put/poznan/transformer/server/logic/TransformsRegister.java
  Server/src/main/java/pl/put/poznan/transformer/server/logic/transform/CaseTransform.java
  Server/src/main/java/pl/put/poznan/transformer/server/logic/transform/DuplicatesRemovalTransform.java
  Server/src/main/java/pl/put/poznan/transformer/server/logic/transform/LaTeXEscapesTransform.java
  Server/src/main/java/pl/put/poznan/transformer/server/logic/transform/NumberExpansionTransform.java
  Server/src/main/java/pl/put/poznan/transformer/server/logic/transform/ReverseTransform.java
  Server/src/main/java/pl/put/poznan/transformer/server/logic/transform/ShortcutTransform.java
  Server/src/main/java/pl/put/poznan/transformer/server/rest/ResponseBody.java
  Server/src/main/java/pl/put/poznan/transformer/server/rest/TextTransformerController.java
  Server/src/main/java/pl/put/poznan/transformer/server/rest/TextTransformerRequestBody.java
  Server/src/main/java/pl/put/poznan/transformer/server/util/DictionaryBuilder.java
  Server/src/main/java/pl/put/poznan/transformer/server/util/JSONFieldDescription.java
  Server/src/main/java/pl/put/poznan/transformer/server/util/PluralVariant.java
  Server/src/main/java/pl/put/poznan/transformer/server/util/PolishPluralVariant.java
  Server/src/main/resources/application.properties
  Server/src/test/java/pl/put/poznan/transformer/logic/transform/CaseTransformTest.java
  Server/src/test/java/pl/put/poznan/transformer/logic/transform/DuplicatesRemovalTransformTest.java
  Server/src/test/java/pl/put/poznan/transformer/logic/transform/LaTeXEscapesTransformTest.java
  Server/src/test/java/pl/put/poznan/transformer/logic/transform/NumberExpansionTransformTest.java
  Server/src/test/java/pl/put/poznan/transformer/logic/transform/ReverseTransformTest.java
  Server/src/test/java/pl/put/poznan/transformer/logic/transform/ShortcutTransformTest.java
  Server/src/test/java/pl/put/poznan/transformer/server/app/TextTransformerServerTest.java
  pom.xml
Labels: documentation, enhancement, test

#13 Dodano obsługę dużych liter dla zdań,
  Client/src/main/java/pl/put/poznan/transformer/client/data/TransformRequest.java
  Diagramy UML.md
  Server/src/main/java/pl/put/poznan/transformer/server/logic/transform/CaseTransform.java
  Server/src/test/java/pl/put/poznan/transformer/logic/transform/CaseTransformTest.java
Labels: documentation, enhancement
